config/routes.rb
Rails.application.routes.draw do
  resources :players, :matches, :match_edits
  root :to => redirect('/players')
end

app/models/match.rb
class Match < ActiveRecord::Base

	has_many :match_edits
	has_many :players, through: :match_edits
	accepts_nested_attributes_for :match_edits, allow_destroy: true, reject_if: proc { |attrs| attrs['result'].blank? }

end

app/models/match_edit.rb
class MatchEdit < ActiveRecord::Base

	belongs_to :match
	belongs_to :player

end

app/models/player.rb
class Player < ActiveRecord::Base

	mount_uploader :picture, PictureUploader

	has_many :match_edits
	has_many :matches, through: :match_edits
	
	def average_result
		sum = 0.0
    	self.match_edits.each do |r|
        	sum += r.result.to_f
    	end
    	avg = sum / self.match_edits.count
	end

	def count_wins
		wins = 0
    	self.match_edits.each do |r|
    		res = r.result.to_f
    		if res == 10
        		wins += 1
        	end 
    	end
    	return wins
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

  respond_to :html

  def index
    @matches = Match.all
  end

  def show
    @match = Match.find(params[:id])
    @results = @match.match_edits
  end

  def new
    @match = Match.new
    @players = Player.all
    2.times {@match.match_edits.build}
  end

  def create
    @match = Match.new(match_params)
    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def match_params
    params[:match].permit :match_date, :match_edits_attributes => [:id, :result, :player_id]
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
    @matches = @player.matches
    @results = @player.match_edits
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:firstname, :lastname, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title OnlineFoosbalTracker
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag "//www.google.com/jsapi", "chartkick"
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default
      .container
        .navbar-header
          %button{:class => 'navbar-toggle', "data-toggle" => 'collapse', "data-target" => ".navbar-collaps"}
            %span{:class => 'sr-only'} Toggle navigation
            %span{:class => 'icon-bar'}
            %span{:class => 'icon-bar'}
            %span{:class => 'icon-bar'}
          %a{:class => "navbar-brand", :href => "/"} Online Foosball Tracker
        .collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li.active
              = link_to 'New Player', new_player_path
            %li.active
              = link_to 'New Match', new_match_path
    .container
      = yield

app/views/matches/index.html.haml
%body
  %header
    %h1 Matches
    = link_to "Add new match", [:new, :match]
  %section

app/views/matches/new.html.haml
= form_for(@match) do |f|
  = f.label :match_date
  = f.date_select :match_date, :order => [:day, :month, :year]

  = f.fields_for :match_edits do |ff|
    = ff.label :player_id, 'Select player'
    = ff.collection_select :player_id, @players, :id, :lastname, {}, { multiple: false }
    = ff.label :result
    = ff.number_field :result, in: 0..10
  %div
    = f.button :submit, id: 'test'

app/views/matches/show.html.haml
#notice
	%p
		= notice

.row
	.col-md-3
		%p
			%b Date:
			= @match.match_date
			%br
			%b Players
			= @match.players.map(&:lastname).join(' vs ')
			%br
			%b Result
			- @results.each do |result|
				= result.result
		%p
			= link_to 'Back', players_path

app/views/players/_form.html.haml
= form_for @player, :html => {:multipart => true} do |f|
  - if @player.errors.any?
    #error_explanation
      %h2= "#{pluralize(@player.errors.count, "error")} prohibited this player from being saved:"
      %ul
        - @player.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :firstname
    = f.text_field :firstname
  .field
    = f.label :lastname
    = f.text_field :lastname
  .field
    = f.label :picture
    = f.file_field :picture
  .actions
    = f.submit 'Save'

app/views/players/edit.html.haml
%h1 Editing player

= render 'form'

= link_to 'Show', @player
\|
= link_to 'Back', players_path

app/views/players/index.html.haml
%h1 Listing players
- @players.in_groups_of(3) do |group|
  .row
    - group.compact.each do |player|
      .col-md-2
        = image_tag player.picture_url(:thumb) if player.picture.present?
        %h4= link_to player.lastname, player

app/views/players/new.html.haml
%h1 New player

= render 'form'

= link_to 'Back', players_path

app/views/players/show.html.haml
#notice
	%p
		= notice

.row
	.col-md-6
		- if @player.picture.present?
			= image_tag @player.picture_url(:avatar)
	.col-md-3
		%p
			%b Firstname:
			= @player.firstname
			%br
			%b Lastname:				
			= @player.lastname
			%br
			%b Average result:
			= @player.average_result
			%br
			%b Number of wins:
			= @player.count_wins
		%p
			= link_to 'Edit', edit_player_path(@player)
			= link_to 'Destroy', @player, data: { confirm: 'Are you sure?' }, method: :delete
			= link_to 'Back', players_path
	.col-md-3
		%p
			%b Match History
			%br
			- @matches.each do |match|
				= link_to match.match_date, match_path